### ISSUE TITLE
Modify DNS so that "www.charlestontechnology.com" resolves properly and shows the homepage

### ISSUE THREAD

**Issue by michaelcippolito** [charlestontechnology/charlestontechnology.github.io#53]
Currently, it appears that only "charlestontechnology.com" is resolving.

I didn't see a way to change this via the repo. The only file I found with any mention of DNS is

https://github.com/charlestontechnology/charlestontechnology.github.io/blob/5d02f75b014bdbe476861b25742df751eaa57f7c/Gemfile.lock

**Comment by rgc** [comment]
@androidfu - this can be fixed with:
www  CNAME   @

in the zone file...
