### ISSUE TITLE
Add SSL certificate 

### ISSUE THREAD

**Issue by oliviasculley** [charlestontechnology/charlestontechnology.github.io#94]
## Problem
http://charlestontechnology.com/ may generate warnings in Chromium or even full page error pages in Firefox with HTTPS-only mode, or if attempting to visit https://charlestontechnology.com

## Warnings from http://charlestontechnology.com/ 
![2024-05-03_14-05-1714760005](https://github.com/charlestontechnology/charlestontechnology.github.io/assets/88074048/21fadb43-9a7f-4f16-8150-e81650d3e07b)
![2024-05-03_14-05-1714759956](https://github.com/charlestontechnology/charlestontechnology.github.io/assets/88074048/18eeb6f8-b1d7-41ec-80eb-b54a360f9a2e)

## Errors with https://charlestontechnology.com
![2024-05-03_14-05-1714760139](https://github.com/charlestontechnology/charlestontechnology.github.io/assets/88074048/ea1a0db6-c5b7-4364-be66-3882e9a67a31)
![2024-05-03_14-05-1714759982](https://github.com/charlestontechnology/charlestontechnology.github.io/assets/88074048/acdcb160-c25c-40ad-a38d-e1e638591498)

Afaik, this should be able to be enabled in Github pages for free, although there might need to be some tweaks to the DNS entries if something is invalid

This is the process that needs to take place: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages

More information:
- https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
- https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by billmote** [comment]
Thank you @oliviasculley. Resolved.
